// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwbmwwozbmexejxgsejb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3Ym13d296Ym1leGVqeGdzZWpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyODM5MDUsImV4cCI6MjA1NTg1OTkwNX0.yDIOw11KxMkSmzpRmaj2Oqi-Lq9WG0ooxWp2UladueI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);